config/routes.rb
Rails.application.routes.draw do
  resources :encoded_items, only: [ :index, :show, :create, :destroy ]
  resources :decoded_items, only: [ :index, :show ]
  resource :main_encoded_item_existence, only: [ :show ]
  namespace :file_backup do
    resource :import, only: [ :create ]
    resource :export, only: [ :create ]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "encoded_items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/encoded_item.rb
class EncodedItem < ApplicationRecord
    PLACEMENT_MIN = 0
    PLACEMENT_MAX = 9
    CYCLE_MIN = 2
    CYCLE_MAX = 10
    MAIN_DESCRIPTOR = "MAIN ENCODED ITEM"

    before_create :apply_encoding_for_create

    def self.with_main_descriptor
        find_by(descriptor: MAIN_DESCRIPTOR)
    end

    def self.does_item_with_main_descriptor_exist?
        with_main_descriptor.present?
    end

    def decode_value
        parsed_placement = decode_placement.to_i
        cycles = self.value[parsed_placement].to_i
        decoded_value = self.value

        apply_base64_in_cycles(
            cycles,
            decoded_value[0, parsed_placement] + decoded_value[parsed_placement + 1, decoded_value.length],
            :decode64
        )
    end

    def decode_placement
        Base64.decode64(self.placement)
    end

    def is_item_with_main_descriptor?
        self.descriptor == MAIN_DESCRIPTOR
    end

    private

    def apply_encoding_for_create
        unencoded_placement = rand(PLACEMENT_MIN..PLACEMENT_MAX)
        cycles = rand(CYCLE_MIN..CYCLE_MAX)
        self.value = apply_base64_in_cycles(cycles, self.value, :encode64)
        self.value.insert(unencoded_placement, cycles.to_s)
        self.placement = Base64.encode64(unencoded_placement.to_s)
    end

    def apply_base64_in_cycles(cycles, apply_to, base64_method)
        result = apply_to
        (0...cycles).each do |cycle|
            result = Base64.send(base64_method, result)
        end

        result
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/main_secret_entry.rb
module MainSecretEntry
  extend ActiveSupport::Concern

  private

  def is_entered_main_secret_valid?
    return false if params["main_secret_entry"].blank?

    main_encoded_item = EncodedItem.with_main_descriptor
    params["main_secret_entry"] == main_encoded_item.decode_value
  end
end

app/controllers/decoded_items_controller.rb
class DecodedItemsController < ApplicationController
    include MainSecretEntry

    def index
        render json: { allowed: false, decoded_items: [] } and return unless is_entered_main_secret_valid?

        render json: {
            allowed: true,
            decoded_items: EncodedItem.all.map { |item| format_item_with_decoded_value(item) }
        }
    end

    def show
        render json: { allowed: false, decoded_item: nil } and return unless is_entered_main_secret_valid?

        render json: {
            allowed: true,
            decoded_item: format_item_with_decoded_value(EncodedItem.find(params[:id]))
        }
    end

    private

    def format_item_with_decoded_value(encoded_item)
        {
            id: encoded_item.id,
            descriptor: encoded_item.descriptor,
            value: encoded_item.decode_value.force_encoding("ISO-8859-1").encode("UTF-8")
        }
    end
end

app/controllers/encoded_items_controller.rb
class EncodedItemsController < ApplicationController
  include MainSecretEntry
  before_action :set_encoded_item, only: %i[ show destroy ]

  # GET /encoded_items or /encoded_items.json
  def index
    @does_main_item_exist = EncodedItem.does_item_with_main_descriptor_exist?
    @encoded_items = EncodedItem.order(created_at: :desc)
  end

  # GET /encoded_items/1 or /encoded_items/1.json
  def show
  end

  # POST /encoded_items or /encoded_items.json
  def create
    @encoded_item = EncodedItem.new(encoded_item_params)

    respond_to do |format|
      if @encoded_item.save
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.prepend(
              "encodedItemsTableBody",
              partial: "encoded_items/encoded_item_row",
              locals: { encoded_item: @encoded_item }
            )
          ]
        end
      else
        # TODO: Remove this html formatting once we make it so that it doesn't reload the entire page on success or fail.
        format.html { redirect_to encoded_items_url, notice: "Encoded item could not be successfully created." }
        format.json { render json: @encoded_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encoded_items/1 or /encoded_items/1.json
  def destroy
    unless is_entered_main_secret_valid?
      render json: { allowed: false } and return
    end

    @encoded_item.destroy!

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove(helpers.dom_id(@encoded_item))
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_encoded_item
      @encoded_item = EncodedItem.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def encoded_item_params
      params.expect(encoded_item: [ :descriptor, :value ])
    end
end

app/controllers/file_backup/exports_controller.rb
module FileBackup
    class ExportsController < ApplicationController
        def create
            items_to_export = EncodedItem.all
            exporter = FileBackup::Exporter.new(items_to_export)
            exporter.export

            send_file exporter.file_path, type: "application/json", filename: File.basename(exporter.file_path)
            rescue StandardError => e
            render json: { error: e.message }, status: :internal_server_error
        end
    end
end

app/controllers/file_backup/imports_controller.rb
class FileBackup::ImportsController < ApplicationController
    def create
        uploaded_file = params[:file]
        if uploaded_file.nil?
            render json: { error: "No file uploaded" }, status: :bad_request
            return
        end

        file_content = uploaded_file.read

        importer = FileBackup::Importer.new(file_content)
        imported_items = importer.import

        render json: { imported_count: imported_items.size }, status: :created
        rescue JSON::ParserError
        render json: { error: "Invalid JSON file" }, status: :unprocessable_entity
    end
end

app/controllers/main_encoded_item_existences_controller.rb
class MainEncodedItemExistencesController < ApplicationController
    def show
        render json: { does_main_encoded_item_exist: EncodedItem.does_item_with_main_descriptor_exist? }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/encoded_items_helper.rb
module EncodedItemsHelper
end

app/views/encoded_items/_encoded_item.html.erb
<div id="<%= dom_id encoded_item %>">
  <p>
    <strong>Descriptor:</strong>
    <%= encoded_item.descriptor %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= encoded_item.value %>
  </p>

</div>

app/views/encoded_items/_encoded_item_row.html.erb
<tr id="<%= dom_id(encoded_item) %>">
  <td><%= encoded_item.descriptor %></td>
  <td><%= encoded_item.value %></td>
  <td>
    <span id="decoded_item_<%= encoded_item.id %>" class="hidden_encoded_value">
      ?
    </span>
  </td>
  <td>
    <button class="td-action-button" onclick="toggleEncodedItemValueDisplay(<%= encoded_item.id %>)">Toggle</button>
    <% unless encoded_item.is_item_with_main_descriptor? %>
      <button class="td-action-button" onclick="showDeleteItemDialogWithItemId(<%= encoded_item.id %>)">Delete</button>
    <% end %>
  </td>
</tr>

app/views/encoded_items/index.html.erb
<%= javascript_include_tag 'encoded_items/index.js' %>

<p style="color: green" class="notice"><%= notice %></p>

<% content_for :title, "Encode It" %>

<div class="surroundingHeader1">
  <h1 class="header1">Encode It</h1>
  <h2 class="subheader1">Your Locally Running Secret Manager</h2>
</div>

<nav class='nav_menu'>
  <ol>
    <li>
      <button id="addNewEncodedItemButton" onclick="showAddNewEncodedItemDialog()">Add a New Encoded Item</button>
    </li>
    <li>
      <button id="exportEncodedItemsButton" onclick="exportEncodedItemsBackupFile()">Export Encoded Items</button>
    </li>
  </ol>
</nav> 


<dialog id="mainSecretEntryDialog">
  <p>Enter the main secret:</p>
  <div class="password-input-group">
    <input autofocus type="password" autocomplete="off" id="mainSecretEntryText" onkeypress="handleMainSecretKeypress(event)">
    <button type="button" onclick="togglePasswordVisibility()" class="toggle-password-btn">Show</button>
  </div><br><br>
  <button onclick='processMainSecretEntrySubmission()'>Submit</button>
</dialog>

<dialog id="accessDeniedDialog">
  <p>You did not enter the correct secret. Decoding failed.</p>
  <button onclick='reopenSecretEntryFromAccessDenied()'>Try Again</button>
</dialog>

<dialog id="deleteItemDialog">
  <p>Are you sure you want to delete this item? This cannot be undone.</p>
  <button id="deleteItemDialogYesButton", onclick="deleteItemFromButtonClick()">Yes</button>
  <button onclick="hideDeleteItemDialog()">No</button> 
</dialog>

<dialog id="exportEncodedItemsDialog">
  <p>A new backup file has been created in the exports directory.</p>
  <button onclick="hideExportEncodedItemsDialog()">OK</button>
</dialog>

<dialog id="addNewMainEncodedItemDialog">
  <form id="newMainEncodedItemForm" action="/encoded_items" accept-charset="UTF-8" method="post" onsubmit="processAddNewMainEncodedItem()">
    <p>Enter a main secret here.</p>
    <p>You'll need to enter it going forward.</p>
    <div class="dialog-form-group">
      <label>Descriptor:</label>
      <input 
        type="text" 
        readOnly=true,
        value="MAIN ENCODED ITEM",
        id="addNewMainEncodedItemDescriptor" 
        name="encoded_item[descriptor]">
    </div>

    <div class="dialog-form-group">
      <label>Value To Encode:</label>
      <input type="text" autocomplete="off" required=true, id="addNewMainEncodedItemValue" name="encoded_item[value]"> 
    </div>
    <br>

    <div>
      <button id="saveNewMainItemButton" type="submit"> Save Item </button>
    </div>
  </form>
</dialog>

<dialog id="addNewEncodedItemDialog">
  <form id="newEncodedItemForm" action="/encoded_items" accept-charset="UTF-8" method="post" onsubmit="processAddNewEncodedItem()">
    <p>Enter details for the new encoded item.</p>
    <div class="dialog-form-group">
      <label>Descriptor:</label>
      <input 
        type="text" 
        autocomplete="off" 
        required=true, 
        id="addNewEncodedItemDescriptor" 
        name="encoded_item[descriptor]"> 
    </div>

    <div class="dialog-form-group">
      <label>Value To Encode:</label>
      <input type="text" autocomplete="off" required=true, id="addNewEncodedItemValue" name="encoded_item[value]"> 
    </div>
    <br>

    <div>
      <button id="saveNewItemButton"> Save Item </button>
      <%if @does_main_item_exist %>
          <button id="cancelButton" onclick="hideAddNewEncodedItemDialog()" >Cancel and Go Back</button>
      <% end %>
    </div>
  </form>
</dialog>

<input type="hidden" id="formAuthenticityToken" value="<%= form_authenticity_token %>">

<div id="encoded_item" class="scrollable-table">
  <table>
    <thead id="encodedItemsTableHeader">
      <tr>
        <th>Descriptor</th>
        <th>Encoded Value</th>
        <th>Decoded Value</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody id="encodedItemsTableBody">
      <% @encoded_items.each do |encoded_item| %>
        <%= render partial: 'encoded_items/encoded_item_row', locals: { encoded_item: encoded_item } %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/encoded_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @encoded_item %>

<div>
  <%= link_to "Back to encoded items", encoded_items_path %>

  <%= button_to "Destroy this encoded item", @encoded_item, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Encode It" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>